steps:

  # Create config directory
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args: [ "-c", "mkdir -p .config/secret/${_ENV}" ]

  # Decrypt secrets
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=secret.${_ENV}.enc
  - --plaintext-file=.config/secret/${_ENV}/secret.env
  - --location=global
  - --keyring=api
  - --key=secret-conf

  # Create .env
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args: [ "-c", "cat .config/secret/${_ENV}/secret.env .config/${_ENV}.env > .env" ]

  # Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

  # Add Cloudbuild network config for compose
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args: [ "-c", 'printf "\nnetworks:\n   default:\n      external:\n        name: cloudbuild" >> docker-compose.yml' ]

  # Spin up MongoDB container for tests
- name: 'docker/compose:1.23.1'
  args: ['up', '-d', 'mongo']

  # Run tests
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  env:
  - 'MONGO_URI=mongodb://root:root@mongo:27017/main-test?authSource=admin'

  # Deploy
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: bash
  args: ["-c", "gcloud app deploy --project=${_PROJECT} app.${_ENV}.yaml --version=${_VERSION:-$SHORT_SHA}"]

timeout: "1600s"
